#!/usr/bin/env python3
"""Derive per-probe comparability between collector generations from git.

`capture/collector/collector.js` has been rewritten five times and no capture
was ever migrated, so the admitted corpus is split across five instruments. The
old rule was that two captures taken by different collectors are not comparable
at all, which stranded 18 of 26 captures including the only full physical Linux
device we own. That rule is far stronger than the evidence: a collector revision
that rewrites the WebGPU probe and leaves the other thirty-five untouched has
not changed what those thirty-five measure.

So comparability is decided PER PROBE, and it is measured rather than declared.
For every revision of the collector reachable from git history this script

  1. slices the file into top-level statements — the probe registrations and the
     module-level helpers they call,
  2. resolves, transitively, which of those helpers each probe's body reaches,
  3. digests the probe's own source together with the source of every helper it
     reaches.

Two generations measure a probe the same way exactly when that digest matches.
Including the helper closure is the part that matters: `webgl1` and `webgl2` are
one-line calls to `webglCapture`, so digesting the registration alone would
call them unchanged across a revision that rewrote the whole WebGL body.

The digest is over the source text verbatim. A whitespace-only reformat
therefore reports as a difference, which is the safe direction: the failure mode
is a probe needlessly skipped, never a probe silently compared across a change.

`capture_version` is read out of each revision too, from the `CAPTURE_VERSION`
literal, so the admission gate can ask "is this the version this collector
emits?" rather than "is this the version the current collector emits". That is
the check that used to strand every pre-v2 capture.

Output: corpus/collector-probe-matrix.json, regenerated by

    python3 scripts/build-collector-matrix.py

Re-running it against the same history reproduces the file byte for byte, which
is what makes the claim falsifiable: anyone can re-extract the collectors and
re-hash them.
"""

import argparse
import hashlib
import json
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
COLLECTOR = "capture/collector/collector.js"
DEFAULT_OUT = REPO / "corpus" / "collector-probe-matrix.json"
RAW_DIR = REPO / "resources" / "fingerprints" / "raw"

# A top-level statement in the collector starts at exactly two spaces of
# indentation. Everything inside one is indented deeper or is its own closing
# line, so the split needs no JavaScript parser and cannot be confused by a
# brace inside a string, a comment or a regular expression.
TOP_LEVEL = re.compile(r"^  (?:function\s+\w+|var\s+\w+|const\s+\w+|let\s+\w+|probe\()")
DEFINITION = re.compile(r"^  (?:function\s+(?P<fn>\w+)|(?:var|const|let)\s+(?P<name>\w+))")
PROBE_ID = re.compile(r'^  probe\(\s*"(?P<id>[^"]+)"')
DETERMINISTIC = re.compile(r"deterministic\s*:\s*true")
CAPTURE_VERSION = re.compile(r"^  var CAPTURE_VERSION = (\d+);", re.MULTILINE)
IDENTIFIER = re.compile(r"[A-Za-z_$][\w$]*")
COMMENT_OR_BLANK = re.compile(r"^\s*(?://|/\*|\*|$)")

# A collector digest with no revision behind it. The source is unrecoverable, so
# there is nothing to hash and no pair it can appear in; recorded here with its
# reason so that "why is this capture stranded?" has a checked-in answer instead
# of being rediscovered from a silent absence.
UNMATRIXABLE_NOTES = {
    "91fe5c48": (
        "Not reachable from git history of capture/collector/collector.js. This "
        "is a locally-modified collector, run once with some checks "
        "deliberately disabled, and the modification was never committed. "
        "Without the source there is nothing to digest, so no probe of a "
        "capture taken with it can be shown comparable to any other "
        "generation's. It stays stranded rather than being trusted on the "
        "strength of agreeing with a sibling capture: agreement with the value "
        "under test is not evidence about the instrument, and 'some checks "
        "disabled' means we cannot even name which probes were weakened. "
        "Nothing is lost by it — the device it measured (the M4 Max) is also "
        "captured on the current collector."
    ),
}


def die(msg):
    print("build-collector-matrix: %s" % msg, file=sys.stderr)
    raise SystemExit(2)


def git(*args):
    done = subprocess.run(("git", "-C", str(REPO)) + args,
                          capture_output=True, check=False)
    if done.returncode != 0:
        die("git %s failed: %s" % (" ".join(args), done.stderr.decode().strip()))
    return done.stdout


def revisions():
    """Every commit that touched the collector, oldest first."""
    out = git("log", "--reverse", "--format=%H", "--", COLLECTOR)
    return out.decode().split()


def chunks(source):
    """Top-level statements, each carrying the comment block above it.

    A comment immediately above a statement documents that statement, so it
    travels with the following chunk rather than trailing the previous one.
    Otherwise a rewritten comment would report as a change to its neighbour.
    """
    lines = source.splitlines(keepends=True)
    starts = [i for i, line in enumerate(lines) if TOP_LEVEL.match(line)]
    out = []
    for n, start in enumerate(starts):
        end = starts[n + 1] if n + 1 < len(starts) else len(lines)
        body = lines[start:end]
        # Give back the trailing comment/blank run: it heads the next statement.
        while len(body) > 1 and COMMENT_OR_BLANK.match(body[-1]):
            body.pop()
        head = start
        while head > 0 and COMMENT_OR_BLANK.match(lines[head - 1]) and \
                lines[head - 1].strip():
            head -= 1
        out.append((head, "".join(lines[head:start]) + "".join(body)))
    return [text for _, text in out]


def dissect(source):
    """-> ({definition name: source}, [(probe id, source, deterministic)])"""
    definitions, probes = {}, []
    for text in chunks(source):
        first = text.splitlines()[0] if text.splitlines() else ""
        for line in text.splitlines():
            if TOP_LEVEL.match(line):
                first = line
                break
        probe_match = PROBE_ID.match(first)
        if probe_match:
            probes.append((probe_match.group("id"), text,
                           bool(DETERMINISTIC.search(text.split("function")[0]))))
            continue
        definition = DEFINITION.match(first)
        if definition:
            name = definition.group("fn") or definition.group("name")
            # A name defined twice would make the closure ambiguous; the
            # collector has never done it, and a silent overwrite would hide it.
            if name in definitions:
                die("%s is defined twice at top level" % name)
            definitions[name] = text
    return definitions, probes


def closure(text, definitions):
    """Every top-level helper the source reaches, transitively."""
    seen, pending = set(), [text]
    while pending:
        for name in set(IDENTIFIER.findall(pending.pop())):
            if name in definitions and name not in seen:
                seen.add(name)
                pending.append(definitions[name])
    return sorted(seen)


def digest(text, deps, definitions):
    h = hashlib.sha256()
    h.update(text.encode("utf-8"))
    for name in deps:
        h.update(b"\0")
        h.update(name.encode("utf-8"))
        h.update(b"\0")
        h.update(definitions[name].encode("utf-8"))
    return h.hexdigest()


def generation(commit):
    blob = git("show", "%s:%s" % (commit, COLLECTOR))
    source = blob.decode("utf-8")
    definitions, probes = dissect(source)
    version = CAPTURE_VERSION.search(source)
    if not version:
        die("%s has no CAPTURE_VERSION literal" % commit)
    entry = {
        "commit": commit[:7],
        "collector_sha256": hashlib.sha256(blob).hexdigest(),
        "capture_version": int(version.group(1)),
        "subject": git("log", "-1", "--format=%s", commit).decode().strip(),
        "committed": git("log", "-1", "--format=%cI", commit).decode().strip(),
        "probes": {},
    }
    for pid, text, deterministic in probes:
        deps = closure(text, definitions)
        entry["probes"][pid] = {
            "deterministic": deterministic,
            "helpers": deps,
            "source_sha256": digest(text, deps, definitions),
        }
    return entry


def pair_matrix(generations):
    """Per-probe verdicts for every ordered pair, keyed a->b.

    Ordered rather than unordered because the interesting asymmetry — which
    generation LOST a probe — is only readable in one direction, and a reader
    holding two captures should not have to know which way to look it up.
    """
    out = {}
    for a_digest, a in sorted(generations.items()):
        for b_digest, b in sorted(generations.items()):
            if a_digest == b_digest:
                continue
            identical, differs, only_a, only_b = [], [], [], []
            for pid in sorted(set(a["probes"]) | set(b["probes"])):
                left, right = a["probes"].get(pid), b["probes"].get(pid)
                if left is None:
                    only_b.append(pid)
                elif right is None:
                    only_a.append(pid)
                elif left["source_sha256"] == right["source_sha256"]:
                    identical.append(pid)
                else:
                    differs.append(pid)
            out["%s->%s" % (a_digest[:8], b_digest[:8])] = {
                "comparable": identical,
                "implementation_differs": differs,
                "only_in_a": only_a,
                "only_in_b": only_b,
            }
    return out


def capture_collectors():
    """Collector digest -> capture names, for the captures we actually hold."""
    out = {}
    for path in sorted(RAW_DIR.glob("*.json")):
        try:
            context = json.loads(path.read_text(encoding="utf-8")).get("context") or {}
        except (OSError, ValueError):
            continue
        collector = context.get("collector_sha256")
        if isinstance(collector, str):
            out.setdefault(collector, []).append(path.name)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true",
                    help="regenerate and compare instead of writing")
    args = ap.parse_args()

    generations = {}
    for commit in revisions():
        entry = generation(commit)
        generations[entry["collector_sha256"]] = entry

    held = capture_collectors()
    unmatrixable = {}
    for collector, names in sorted(held.items()):
        if collector in generations:
            continue
        note = UNMATRIXABLE_NOTES.get(collector[:8])
        if note is None:
            die("captures %s were taken with collector %s, which is not in git "
                "history and has no recorded reason; add one to "
                "UNMATRIXABLE_NOTES or recover the revision"
                % (", ".join(names), collector[:8]))
        unmatrixable[collector] = {"captures": names, "reason": note}

    document = {
        "schema": "apostate/corpus/collector-probe-matrix/1",
        "generated_by": "scripts/build-collector-matrix.py",
        "source": COLLECTOR,
        "method": (
            "Each generation is the collector file at a commit that touched it. "
            "A probe's source digest covers its registration plus the "
            "transitive closure of the module-level helpers it calls, verbatim. "
            "Two generations are comparable for a probe exactly when that "
            "digest matches; a probe present in one and absent in the other is "
            "reported rather than compared."
        ),
        "generations": generations,
        "pairs": pair_matrix(generations),
        "unmatrixable": unmatrixable,
    }
    encoded = json.dumps(document, sort_keys=True, separators=(",", ":")) + "\n"

    if args.check:
        try:
            existing = args.out.read_text(encoding="utf-8")
        except OSError as exc:
            die("cannot read %s: %s" % (args.out, exc))
        if existing != encoded:
            die("%s is stale; re-run scripts/build-collector-matrix.py"
                % args.out.relative_to(REPO))
        print("%s is current" % args.out.relative_to(REPO))
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(encoded, encoding="utf-8")
    print("%s: %d generation(s), %d pair(s), %d unmatrixable collector(s)"
          % (args.out.relative_to(REPO), len(generations),
             len(document["pairs"]), len(unmatrixable)))
    for collector, entry in sorted(generations.items()):
        print("  %s  %s  v%d  %2d probe(s)  %s"
              % (collector[:8], entry["commit"], entry["capture_version"],
                 len(entry["probes"]), entry["subject"][:52]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
