#!/usr/bin/env bash
# Full build, then write build/MANIFEST.lock recording exactly what produced it.
source "$(dirname "$0")/lib.sh"

TARGET="${1:-$(target_default)}"
OUT="$SRC/out/$TARGET"
[ -f "$OUT/args.gn" ] || die "not configured; run scripts/configure.sh $TARGET"

# Leave headroom by default. On a shared machine an unconstrained Chromium build
# starves everything else, and where the box also runs latency-sensitive work a
# saturated scheduler distorts its measurements.
JOBS="${APOSTATE_JOBS:-$(python3 -c "import os;print(max(1,int(os.cpu_count()*0.75)))")}"

say "building $TARGET with $JOBS jobs"
( cd "$SRC" && nice -n 10 autoninja -j "$JOBS" -C "out/$TARGET" chrome )

manifest="$REPO_ROOT/build/MANIFEST.lock"
{
  echo "# Generated by scripts/build.sh. Records what this build resolved."
  echo "built_at             = \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
  echo "target               = \"$TARGET\""
  echo "chromium_version     = \"$CHROMIUM_VERSION\""
  echo "chromium_commit      = \"$(git -C "$SRC" rev-parse HEAD)\""
  echo "depot_tools_revision = \"$DEPOT_TOOLS_REVISION\""
  echo "patch_series_sha256  = \"$(shasum -a 256 "$REPO_ROOT/patches/series" | cut -d' ' -f1)\""
  echo "args_sha256          = \"$(shasum -a 256 "$OUT/args.gn" | cut -d' ' -f1)\""
  echo
  echo "[outputs]"
  for f in chrome chrome_crashpad_handler libEGL.so libGLESv2.so Chromium.app; do
    [ -e "$OUT/$f" ] || continue
    if [ -d "$OUT/$f" ]; then
      echo "\"$f\" = \"dir:$(find "$OUT/$f" -type f -exec shasum -a 256 {} + | sort | shasum -a 256 | cut -d' ' -f1)\""
    else
      echo "\"$f\" = \"$(shasum -a 256 "$OUT/$f" | cut -d' ' -f1)\""
    fi
  done
} > "$manifest"

say "wrote $manifest"
grep -A20 '\[outputs\]' "$manifest"
