#!/usr/bin/env bash
# Write args.gn from the pinned target file and run gn gen.
source "$(dirname "$0")/lib.sh"

if [ "${1:-$(target_default)}" = macos-arm64 ] && [ "$(uname -s)" != Darwin ]; then
  die "macos-arm64 configuration requires a native macOS runner"
fi
if [ "$(uname -s)" = Linux ] && [ -z "${APOSTATE_BUILD_IMAGE_ID:-}" ]; then
  exec bash "$REPO_ROOT/scripts/in-linux-build-container.sh" scripts/configure.sh "$@"
fi

TARGET="${1:-$(target_default)}"
ARGS_FILE="$REPO_ROOT/build/args/$TARGET.gn"
[ -f "$ARGS_FILE" ] || die "no args for target '$TARGET' (build/args/$TARGET.gn)"
[ -d "$SRC" ] || die "no checkout; run scripts/fetch-sources.sh"

OUT="$SRC/out/$TARGET"

# Hosted CI always requests an empty out/ directory so the manifest records a
# fresh build. Local builds retain incremental output unless explicitly reset.
if [ "${APOSTATE_FRESH_BUILD:-}" = "1" ]; then
  rm -rf "$OUT"
fi

mkdir -p "$OUT"

# gn imports visual_studio_version.gni, which runs vs_toolchain.py
# get_toolchain_dir and aborts the whole generate if it cannot resolve a
# toolchain. Run exactly that command first, so the failure names the cause
# instead of arriving as a gn import backtrace after the sync. This is the
# real predicate rather than a proxy for it: verify-host-tooling.sh can only
# confirm Visual Studio exists, and it did exactly that on a runner where gn
# then failed, because vs_toolchain.py looks for 2022 under %ProgramFiles%
# while the hosted images install Build Tools into the x86 tree. lib.sh
# exports vs2022_install to bridge that; this checks the bridge held.
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*)
    if ! python3 "$SRC/build/vs_toolchain.py" get_toolchain_dir >/dev/null 2>&1; then
      printf '==> vs_toolchain.py get_toolchain_dir failed:\n' >&2
      python3 "$SRC/build/vs_toolchain.py" get_toolchain_dir >&2 2>&1 || true
      die "Chromium cannot resolve a Visual Studio toolchain (vs2022_install=${vs2022_install:-<unset>}); gn would fail at build/config/win/visual_studio_version.gni"
    fi

    # build/WINDOWS_SDK_VERSION mirrors the SDK_VERSION that build/vs_toolchain.py
    # hardcodes, so scripts/verify-host-tooling.sh can assert the SDK's Include
    # and Lib trees before a checkout exists to read it from. A mirror nothing
    # compares is a mirror that drifts, and this drift would be silent in the
    # worst direction: the preflight would confirm an SDK version this build
    # does not use and pass. This is the first step where both halves exist.
    _want_sdk="$(tr -d '[:space:]' < "$REPO_ROOT/build/WINDOWS_SDK_VERSION")"
    _have_sdk="$(sed -n "s/^SDK_VERSION = '\([^']*\)'.*/\1/p" \
      "$SRC/build/vs_toolchain.py" | head -1)"
    [ -n "$_have_sdk" ] ||
      die "could not read SDK_VERSION out of $SRC/build/vs_toolchain.py; the preflight's SDK paths cannot be trusted"
    [ "$_want_sdk" = "$_have_sdk" ] ||
      die "build/WINDOWS_SDK_VERSION says $_want_sdk but build/vs_toolchain.py uses $_have_sdk.
Chromium chooses this version, not us. Update build/WINDOWS_SDK_VERSION to
$_have_sdk; scripts/verify-host-tooling.sh has been checking the wrong SDK trees."
    say "windows sdk $_have_sdk (build/WINDOWS_SDK_VERSION agrees)"
    unset _want_sdk _have_sdk
    ;;
esac

# The pinned SDK is resolved and linked before args.gn is written, so the
# generated args name a source-relative path that is identical on every host.
# Without this, Chromium picks the newest SDK the active Xcode provides and an
# Xcode upgrade silently changes a build input.
MAC_SDK_PATH=""
if [ "$TARGET" = macos-arm64 ]; then
  MAC_SDK_PATH="//out/$TARGET/$(bash "$REPO_ROOT/scripts/prepare-mac-sdk.sh" "$OUT" | tail -1)"
fi

# args.gn is assembled by concatenation rather than by a gn import, so nothing
# has to be planted inside the checkout, and it makes args.gn self-contained:
# MANIFEST.lock's args_sha256 then covers the full effective configuration
# rather than a file that points at another file.
{
  echo "# Generated by scripts/configure.sh from build/args/common.gni"
  echo "# and build/args/$TARGET.gn. Do not edit; edit those."
  echo
  cat "$REPO_ROOT/build/args/common.gni"
  echo
  grep -v '^import(' "$ARGS_FILE"
  if [ -n "$MAC_SDK_PATH" ]; then
    echo
    echo "# Pinned by build/MAC_SDK_VERSION via scripts/prepare-mac-sdk.sh."
    echo "mac_sdk_path = \"$MAC_SDK_PATH\""
  fi
} > "$OUT/args.gn"
[ -x "$GN" ] || die "no gn at $GN; the checkout is incomplete"

say "configuring $TARGET with $("$GN" --version)"
# compile_commands.json in the same pass — it is what makes the V1 single-file
# gate possible, and a second gn gen would only regenerate the same ninja files.
( cd "$SRC" && "$GN" gen "out/$TARGET" --export-compile-commands )
say "configured  out/$TARGET  ($(wc -l < "$OUT/args.gn") args)"
