#!/usr/bin/env bash
# Write args.gn from the pinned target file and run gn gen.
source "$(dirname "$0")/lib.sh"

if [ "${1:-$(target_default)}" = macos-arm64 ] && [ "$(uname -s)" != Darwin ]; then
  die "macos-arm64 configuration requires a native macOS runner"
fi
if [ "$(uname -s)" = Linux ] && [ -z "${APOSTATE_BUILD_IMAGE_ID:-}" ]; then
  exec bash "$REPO_ROOT/scripts/in-linux-build-container.sh" scripts/configure.sh "$@"
fi

TARGET="${1:-$(target_default)}"
ARGS_FILE="$REPO_ROOT/build/args/$TARGET.gn"
[ -f "$ARGS_FILE" ] || die "no args for target '$TARGET' (build/args/$TARGET.gn)"
[ -d "$SRC" ] || die "no checkout; run scripts/fetch-sources.sh"

OUT="$SRC/out/$TARGET"

# Hosted CI always requests an empty out/ directory so the manifest records a
# fresh build. Local builds retain incremental output unless explicitly reset.
if [ "${APOSTATE_FRESH_BUILD:-}" = "1" ]; then
  rm -rf "$OUT"
fi

mkdir -p "$OUT"

# The pinned SDK is resolved and linked before args.gn is written, so the
# generated args name a source-relative path that is identical on every host.
# Without this, Chromium picks the newest SDK the active Xcode provides and an
# Xcode upgrade silently changes a build input.
MAC_SDK_PATH=""
if [ "$TARGET" = macos-arm64 ]; then
  MAC_SDK_PATH="//out/$TARGET/$(bash "$REPO_ROOT/scripts/prepare-mac-sdk.sh" "$OUT" | tail -1)"
fi

# args.gn is assembled by concatenation rather than by a gn import, so nothing
# has to be planted inside the checkout, and it makes args.gn self-contained:
# MANIFEST.lock's args_sha256 then covers the full effective configuration
# rather than a file that points at another file.
{
  echo "# Generated by scripts/configure.sh from build/args/common.gni"
  echo "# and build/args/$TARGET.gn. Do not edit; edit those."
  echo
  cat "$REPO_ROOT/build/args/common.gni"
  echo
  grep -v '^import(' "$ARGS_FILE"
  if [ -n "$MAC_SDK_PATH" ]; then
    echo
    echo "# Pinned by build/MAC_SDK_VERSION via scripts/prepare-mac-sdk.sh."
    echo "mac_sdk_path = \"$MAC_SDK_PATH\""
  fi
} > "$OUT/args.gn"
[ -x "$GN" ] || die "no gn at $GN; the checkout is incomplete"

say "configuring $TARGET with $("$GN" --version)"
# compile_commands.json in the same pass — it is what makes the V1 single-file
# gate possible, and a second gn gen would only regenerate the same ninja files.
( cd "$SRC" && "$GN" gen "out/$TARGET" --export-compile-commands )
say "configured  out/$TARGET  ($(wc -l < "$OUT/args.gn") args)"
