#!/usr/bin/env python3
"""Export the actual private baseline/HEVC object/config delta, preserving targets.

Uses the DEPS-pinned upstream generator's source mapping, include scanner, license
checks, credit generation and collision wrapper convention. Both variants must
have built successfully. Does not replace the full upstream target matrix with a
single-target generation.
"""
import argparse, hashlib, json, os, re, sys
from pathlib import Path

CONFIGS = ['config.h','config.asm','config_components.h','config_components.asm',
           'libavcodec/codec_list.c','libavcodec/parser_list.c']

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--work',required=True,type=Path)
    args=parser.parse_args(); work=args.work.resolve()
    receipt=json.loads((work/'receipt.json').read_text())
    assert receipt['ffmpeg_revision']=='2b68d2babae73714846961fb0ee47e3b3d2e39a9'
    assert all(receipt['variants'][v]['build']['passed'] for v in ['baseline','hevc'])
    source=work/'hevc/src/third_party/ffmpeg'
    sys.path.insert(0,str(work/'hevc/src/media/ffmpeg/scripts'))
    import generate_gn as g
    mapping=g.GetObjectToSourceMapping(g.GetSourceFiles(str(source)))
    sets={v:g.GetSourceFileSet(mapping,g.GetObjectFiles(str(work/v/'src/third_party/ffmpeg/build.x64.linux/Chrome'))) for v in ['baseline','hevc']}
    assert not sets['baseline']-sets['hevc'], 'unexpected removed sources'
    added=sorted(sets['hevc']-sets['baseline']); assert added
    changes={}
    for name in CONFIGS:
        before=(work/'baseline/src/third_party/ffmpeg/build.x64.linux/Chrome'/name).read_text()
        after=(work/'hevc/src/third_party/ffmpeg/build.x64.linux/Chrome'/name).read_text()
        target='chromium/config/Chrome/linux/x64/'+name
        original=(source/target).read_text(); revised=original
        if name.startswith('config'):
            # Import only actual changed macro definitions, not host/compiler paths.
            pattern=r'^(?:#|%)define (\w+) (.*)$'
            old=dict(re.findall(pattern,before,re.M)); new=dict(re.findall(pattern,after,re.M))
            assert old.keys()==new.keys()
            for key in old:
                if old[key] == new[key]:continue
                old_line=('#' if name.endswith('.h') else '%')+'define '+key+' '+old[key]
                new_line=('#' if name.endswith('.h') else '%')+'define '+key+' '+new[key]
                assert revised.splitlines().count(old_line)==1, key
                revised=revised.replace(old_line+'\n',new_line+'\n')
            if name=='config.h':
                anchor='" -- elide long configuration string from binary */'
                assert revised.count(anchor)==1
                revised=revised.replace(anchor,' --enable-decoder=hevc --enable-parser=hevc'+anchor)
        else:
            assert original==before, 'registration baseline differs: '+name
            revised=after
        if revised!=original:changes[target]={'before':original,'after':revised}
    gni='ffmpeg_generated.gni'; original=(source/gni).read_text()
    existing=set(re.findall(r'"([^"\n]+\.(?:c|S|asm))"',original))
    stems={Path(name).stem for name in existing}
    generated=[]; wrappers={}; replaced=[]
    for name in added:
        stem=Path(name).stem
        if stem in stems:
            renamed=str(Path(name).parent/('autorename_'+'_'.join(name.split('/'))))
            assert Path(renamed).stem not in stems
            prefix='%' if name.endswith('.asm') else '#'
            comment=';' if name.endswith('.asm') else '//'
            content=(f'{comment} Generated by export-hevc-ffmpeg-delta.py from pinned FFmpeg objects.\n'
                     f'{prefix}include "../../third_party/ffmpeg/{name}"\n')
            assert not (source/renamed).exists(), 'unexpected existing wrapper'
            wrappers[renamed]=content; generated.append(renamed); replaced.append(name)
            stems.add(Path(renamed).stem)
        else:
            generated.append(name); stems.add(stem)
    # The copied Chrome/linux/x64 config is also used by ChromeOS/Fuchsia. MSAN
    # selects linux-noasm and must never receive these asm-dependent objects.
    stanza='\n# Generated from real baseline/HEVC builds; other target sets are retained.\n'
    stanza+='if (ffmpeg_branding == "Chrome" && current_cpu == "x64" && os_config == "linux") {\n'
    groups={'ffmpeg_c_sources':[n for n in generated if n.endswith('.c')],
            'ffmpeg_asm_sources':[n for n in generated if n.endswith('.asm')],
            'ffmpeg_gas_sources':[n for n in generated if n.endswith('.S')],
            'ffmpeg_c_deps':[n for n in replaced if n.endswith('.c')],
            'ffmpeg_asm_deps':[n for n in replaced if n.endswith('.asm')],
            'ffmpeg_asm_include_dirs':['//third_party/ffmpeg/'+n for n in sorted({str(Path(n).parent) for n in added if n.endswith('.asm')})]}
    for variable,values in groups.items():
        if not values:continue
        stanza+='  '+variable+' += [\n'+''.join('    "'+v+'",\n' for v in sorted(values))+'  ]\n'
    stanza+='}\n'
    changes[gni]={'before':original,'after':original+stanza}
    includes=set()
    os.chdir(source)
    # Include all previous targets when regenerating credits; never drop their
    # attribution while adding the HEVC files from this one target.
    for name in sorted(existing|set(added)):
        g.GetIncludedSources(name,str(source),includes)
    includes={n for n in includes if not g.RENAME_REGEX.search(n)}
    assert g.CheckLicensesForStaticLinking(sorted(includes),str(source),False)
    credits=(source/'CREDITS.chromium').read_text()
    g.UpdateCredits(sorted(includes),str(source))
    updated=(source/'CREDITS.chromium').read_text()
    if updated!=credits:changes['CREDITS.chromium']={'before':credits,'after':updated}
    for name,content in wrappers.items():changes[name]={'before':None,'after':content}
    export={'ffmpeg_revision':receipt['ffmpeg_revision'],'chromium_revision':receipt['chromium_revision'],
            'added_sources':added,'removed_sources':[],'wrappers':sorted(wrappers),'license_files_checked':len(includes),
            'generated_groups':groups,'changes':{'third_party/ffmpeg/'+p:v for p,v in changes.items()}}
    (work/'ffmpeg-delta.json').write_text(json.dumps(export,indent=2)+'\n')
    print(json.dumps({'added_objects':len(added),'changed_files':len(changes),'license_files_checked':len(includes),'wrappers':sorted(wrappers)}))
if __name__=='__main__':main()
