#!/usr/bin/env python3
"""Build a fontconfig that makes a Linux host enumerate a claimed device's fonts.

Font enumeration is not a structural limit. Chromium on Linux asks fontconfig,
and fontconfig answers from whatever configuration it is pointed at — so the
font set a page can detect is entirely a provisioning decision. Measured on the
build host: pointing FONTCONFIG_FILE at a config listing one directory made
Chromium enumerate exactly the families in that directory and nothing else.

Two halves, and the second is the one that gets missed.

**Add** the families the claimed device has. That needs the actual font files;
they are licensed and are not in this repository. The operator supplies them.

**Removal matters less than it looks.** This config replaces the system font
path rather than extending it, so the host's own families drop out by default —
but that is tidiness, not the point. Presence of a foreign family proves little:
Liberation and DejaVu arrive with LibreOffice on any platform, Noto with all
sorts of software, and real machines carry whatever their owners installed.
Measured against the reference Mac, removal accounts for 3 differing fields and
installation for 26.

What cannot be explained away is the *absence* of families the claimed platform
ships and cannot uninstall — Menlo, Monaco, Zapfino, PingFang SC, Helvetica Neue
on macOS. That is what this tool reports.

Usage:
    scripts/make-fontconfig.py --fonts /srv/fonts/macos \\
        --reference resources/fingerprints/raw/CAPTURE.json \\
        --out /srv/fonts/macos.conf

    FONTCONFIG_FILE=/srv/fonts/macos.conf apostate --apostate-profile=...

With --reference it reports which of the reference device's families the
directory supplies and which are still missing, so provisioning is measured
rather than assumed.
"""

import argparse
import json
import pathlib
import subprocess
import sys

TEMPLATE = """<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- Generated by scripts/make-fontconfig.py. Do not edit by hand.
     Replaces the system font path entirely: families outside %(fontdir)s are
     not visible to the browser, which is how the host's own fonts are kept out
     of a profile that claims another platform. -->
<fontconfig>
  <dir>%(fontdir)s</dir>
  <cachedir>%(cachedir)s</cachedir>

  <!-- Generic aliases must resolve inside the supplied set, or text falls back
       to nothing and every width collapses to one value. -->
%(aliases)s
</fontconfig>
"""

ALIAS = """  <match target="pattern">
    <test qual="any" name="family"><string>%s</string></test>
    <edit name="family" mode="prepend" binding="strong"><string>%s</string></edit>
  </match>"""


def families_in(fontdir: pathlib.Path, conf: pathlib.Path) -> set:
    try:
        out = subprocess.run(["fc-list", ":", "family"], capture_output=True,
                             text=True, env={"FONTCONFIG_FILE": str(conf),
                                             "PATH": "/usr/bin:/bin"})
    except FileNotFoundError:
        return set()
    fams = set()
    for line in out.stdout.splitlines():
        for f in line.split(","):
            if f.strip():
                fams.add(f.strip())
    return fams


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fonts", type=pathlib.Path, required=True,
                    help="directory of font files the operator supplies")
    ap.add_argument("--out", type=pathlib.Path, required=True)
    ap.add_argument("--cache", type=pathlib.Path,
                    help="fontconfig cache dir (default: <out>.cache)")
    ap.add_argument("--reference", type=pathlib.Path,
                    help="T0 capture whose font list the directory should supply")
    ap.add_argument("--serif", default="Times New Roman")
    ap.add_argument("--sans", default="Arial")
    ap.add_argument("--monospace", default="Courier New")
    args = ap.parse_args()

    if not args.fonts.is_dir():
        print("no such font directory: %s" % args.fonts, file=sys.stderr)
        return 2

    cache = args.cache or pathlib.Path(str(args.out) + ".cache")
    cache.mkdir(parents=True, exist_ok=True)

    aliases = "\n".join(ALIAS % (generic, family) for generic, family in
                        (("serif", args.serif), ("sans-serif", args.sans),
                         ("monospace", args.monospace)))
    args.out.write_text(TEMPLATE % {"fontdir": args.fonts.resolve(),
                                    "cachedir": cache.resolve(),
                                    "aliases": aliases})
    print("wrote %s" % args.out)
    print("  use with: FONTCONFIG_FILE=%s" % args.out.resolve())

    if args.reference:
        cap = json.loads(args.reference.read_text())
        probe = cap.get("probes", {}).get("fonts.detected")
        if not (probe and probe.get("ok")):
            print("  reference has no usable fonts.detected probe", file=sys.stderr)
            return 0
        want = set(probe["value"]["detected"])
        have = families_in(args.fonts, args.out)
        missing = sorted(f for f in want if f not in have)
        print()
        print("  reference wants %d families, directory supplies %d"
              % (len(want), len(want) - len(missing)))
        if missing:
            print("  MISSING (%d): %s" % (len(missing), ", ".join(missing)))
            print()
            print("  These are licensed files and are not distributable with this")
            print("  repository. Copy them from a machine entitled to them.")
        else:
            print("  every reference family is present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
