#!/usr/bin/env python3
"""Build a fontconfig that makes a Linux host enumerate a claimed device's fonts.

Font enumeration is not a structural limit. Chromium on Linux asks fontconfig,
and fontconfig answers from whatever configuration it is pointed at — so the
font set a page can detect is entirely a provisioning decision. Measured on the
build host: pointing FONTCONFIG_FILE at a config listing one directory made
Chromium enumerate exactly the families in that directory and nothing else.

Two halves, and the second is the one that gets missed.

**Add** the families the claimed device has. That needs the actual font files;
they are licensed and are not in this repository. The operator supplies them.

**Removal matters less than it looks.** This config replaces the system font
path rather than extending it, so the host's own families drop out by default —
but that is tidiness, not the point. Presence of a foreign family proves little:
Liberation and DejaVu arrive with LibreOffice on any platform, Noto with all
sorts of software, and real machines carry whatever their owners installed.
Measured against the reference Mac, removal accounts for 3 differing fields and
installation for 26.

What cannot be explained away is the *absence* of families the claimed platform
ships and cannot uninstall — Menlo, Monaco, Zapfino, PingFang SC, Helvetica Neue
on macOS. That is what this tool reports.

Usage:
    scripts/make-fontconfig.py --fonts /srv/fonts/macos \\
        --reference resources/fingerprints/raw/CAPTURE.json \\
        --out /srv/fonts/macos.conf

    FONTCONFIG_FILE=/srv/fonts/macos.conf apostate --apostate-profile=...

With --reference it reports which of the reference device's families the
directory supplies and which are still missing, so provisioning is measured
rather than assumed.
"""

import argparse
import json
import pathlib
import subprocess
import sys

TEMPLATE = """<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- Generated by scripts/make-fontconfig.py. Do not edit by hand.
     Replaces the system font path entirely: families outside %(fontdir)s are
     not visible to the browser, which is how the host's own fonts are kept out
     of a profile that claims another platform. -->
<fontconfig>
  <dir>%(fontdir)s</dir>
  <cachedir>%(cachedir)s</cachedir>

  <!-- Generic aliases must resolve inside the supplied set, or text falls back
       to nothing and every width collapses to one value. -->
%(aliases)s

  <!-- Hinting off, and this is the setting that decides whether metrics match.
       FreeType hints glyph advances by default; DirectWrite and CoreText report
       the font's own linear metrics. With hinting on, a correctly provisioned
       host still disagreed with the reference on 68 of 76 families by a median
       of 5 units in ~700. With it off, 75 of 76 agree exactly and the three
       generic baselines match to the unit. -->
  <match target="font">
    <edit name="hinting" mode="assign"><bool>false</bool></edit>
    <edit name="hintstyle" mode="assign"><const>hintnone</const></edit>
    <edit name="antialias" mode="assign"><bool>true</bool></edit>
    <edit name="rgba" mode="assign"><const>none</const></edit>
  </match>
%(emoji)s%(rejects)s</fontconfig>
"""

ALIAS = """  <match target="pattern">
    <test qual="any" name="family"><string>%s</string></test>
    <edit name="family" mode="prepend" binding="strong"><string>%s</string></edit>
  </match>"""


def families_in(fontdir: pathlib.Path, conf: pathlib.Path) -> set:
    try:
        out = subprocess.run(["fc-list", ":", "family"], capture_output=True,
                             text=True, env={"FONTCONFIG_FILE": str(conf.resolve()),
                                             "PATH": "/usr/bin:/bin"})
    except FileNotFoundError:
        return set()
    fams = set()
    for line in out.stdout.splitlines():
        for f in line.split(","):
            if f.strip():
                fams.add(f.strip())
    return fams


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fonts", type=pathlib.Path, required=True,
                    help="directory of font files the operator supplies")
    ap.add_argument("--out", type=pathlib.Path, required=True)
    ap.add_argument("--cache", type=pathlib.Path,
                    help="fontconfig cache dir (default: <out>.cache)")
    ap.add_argument("--reference", type=pathlib.Path,
                    help="T0 capture whose font list the directory should supply")
    ap.add_argument("--subject", type=pathlib.Path,
                    help="a capture taken from THIS host WITHOUT rejection "
                         "rules. With --reference, families this host enumerated "
                         "and the reference did not are rejected. Two-pass by "
                         "necessity: what a host enumerates cannot be predicted "
                         "from the directory, only measured. Feeding back a "
                         "capture that already had rejects applied finds no "
                         "surplus and silently drops them.")
    ap.add_argument("--serif", default="Times New Roman")
    ap.add_argument("--sans", default="Arial")
    ap.add_argument("--monospace", default="Courier New")
    ap.add_argument("--emoji", help="colour emoji family for the generic "
                                    "'emoji' alias, e.g. 'Segoe UI Emoji'")
    ap.add_argument("--alias", action="append", default=[], metavar="OLD=NEW",
                    help="map a family name onto another, repeatable. Real "
                         "platforms do this: Windows resolves Helvetica to "
                         "Arial and Times to Times New Roman through its font "
                         "mapper, with no such file on disk, so a host that "
                         "only has the files under-reports against a real "
                         "machine unless the same mappings are declared.")
    args = ap.parse_args()

    if not args.fonts.is_dir():
        print("no such font directory: %s" % args.fonts, file=sys.stderr)
        return 2

    cache = args.cache or pathlib.Path(str(args.out) + ".cache")
    cache.mkdir(parents=True, exist_ok=True)
    # families_in() reads the directory through a config, so a minimal one has
    # to exist before the surplus can be computed.
    if not args.out.exists():
        args.out.write_text(TEMPLATE % {"fontdir": args.fonts.resolve(),
                                        "cachedir": cache.resolve(),
                                        "aliases": "", "emoji": "", "rejects": ""})

    pairs = [("serif", args.serif), ("sans-serif", args.sans),
             ("monospace", args.monospace)]
    for a in args.alias:
        if "=" not in a:
            print("--alias needs OLD=NEW, got %r" % a, file=sys.stderr)
            return 2
        old_name, new_name = a.split("=", 1)
        pairs.append((old_name.strip(), new_name.strip()))
    aliases = "\n".join(ALIAS % (src, dst) for src, dst in pairs)
    # Reject families the directory supplies that the reference device does not
    # report. A font export taken off a machine contains everything on its disk,
    # and a disk holds fonts the system never activates — Book Antiqua, Bookman
    # Old Style, Century Gothic and Century Schoolbook were all present in a
    # complete macOS export and absent from what that same machine enumerates.
    # Provisioning them made conformance worse, not better: the target is the
    # set the reference reports, not the set it stores.
    rejects = ""
    if args.reference and args.subject:
        det = {d.lower() for d in
               json.loads(args.reference.read_text())["probes"]
               ["fonts.detected"]["value"]["detected"]}
        mine = json.loads(args.subject.read_text())["probes"] \
                   ["fonts.detected"]["value"]["detected"]
        # Only what this host actually enumerated and the reference did not.
        # Deriving the surplus from the font directory instead was wrong: it
        # rejected Apple Color Emoji and Arial Hebrew, which the reference has
        # and the width-comparison probe simply cannot see — a colour emoji face
        # renders Latin text at the fallback width, so it reads as absent. A
        # font being undetectable is not a font being absent.
        surplus = sorted(f for f in mine if f.lower() not in det)
        if True:
            if surplus:
                rejects = "\n  <selectfont>\n" + "\n".join(
                    '    <rejectfont><pattern><patelt name="family">'
                    '<string>%s</string></patelt></pattern></rejectfont>' % s
                    for s in surplus) + "\n  </selectfont>\n"

    emoji = ""
    if args.emoji:
        emoji = ('  <alias binding="strong"><family>emoji</family>'
                 '<prefer><family>%s</family></prefer></alias>\n' % args.emoji)
    args.out.write_text(TEMPLATE % {"fontdir": args.fonts.resolve(),
                                    "cachedir": cache.resolve(),
                                    "aliases": aliases,
                                    "emoji": emoji,
                                    "rejects": rejects})
    print("wrote %s" % args.out)
    print("  use with: FONTCONFIG_FILE=%s" % args.out.resolve())

    if args.reference:
        cap = json.loads(args.reference.read_text())
        probe = cap.get("probes", {}).get("fonts.detected")
        if not (probe and probe.get("ok")):
            print("  reference has no usable fonts.detected probe", file=sys.stderr)
            return 0
        want = set(probe["value"]["detected"])
        have = families_in(args.fonts, args.out)
        # Case-insensitive: CSS font matching is, and a reference capture may
        # carry a family in whatever case the probe list used. Comparing
        # case-sensitively reported Lucida Grande missing from a directory that
        # contained it.
        have_lower = {h.lower() for h in have}
        # An aliased family is satisfied without its own file, and saying
        # otherwise sends the operator hunting for fonts they do not need.
        # Windows itself resolves several of these through the registry's
        # FontSubstitutes key rather than shipping a file: Helvetica is Arial,
        # Times is Times New Roman, Courier is Courier New, MS Sans Serif is
        # Microsoft Sans Serif. A page that measures them sees the substitute,
        # which is exactly what --alias reproduces.
        aliased = {src.lower() for src, dst in pairs if dst.lower() in have_lower}
        satisfied = have_lower | aliased
        missing = sorted(f for f in want if f.lower() not in satisfied)
        print()
        print("  reference wants %d families, directory supplies %d"
              % (len(want), len(want) - len(missing)))
        if aliased:
            covered = sorted(f for f in want if f.lower() in aliased)
            if covered:
                print("  satisfied by substitution (%d): %s"
                      % (len(covered), ", ".join(covered)))
        if missing:
            print("  MISSING (%d): %s" % (len(missing), ", ".join(missing)))
            print()
            print("  These are licensed files and are not distributable with this")
            print("  repository. Copy them from a machine entitled to them.")
        else:
            print("  every reference family is present or substituted")
    return 0


if __name__ == "__main__":
    sys.exit(main())
