#!/usr/bin/env python3
"""Validate the checked-in release baseline without requiring a Chromium checkout.

The build manifest is generated by ``scripts/build.sh``.  This checker verifies
only inputs available in the source repository, so it is suitable for pull
request gates before a generated checkout exists.
"""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
from pathlib import Path
import re
import sys
from typing import Iterable


_HASH_RE = re.compile(r"^[0-9a-f]{64}$")
_VERSION_RE = re.compile(r"^[0-9]+(?:\.[0-9]+){3,4}$")
_ASSIGNMENT_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$")


class ValidationError(Exception):
    """Raised for an invalid release baseline."""


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _read_manifest(path: Path) -> dict[str, str]:
    """Read scalar key/value fields from the build manifest.

    MANIFEST.lock is deliberately a small generated format rather than a
    general TOML document.  Parse the scalar section strictly enough to catch
    truncation and malformed values while ignoring the output hash table.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        raise ValidationError(f"cannot read MANIFEST.lock: {error}") from error

    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(text.splitlines(), 1):
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("#"):
            continue
        if line == "[outputs]":
            break
        match = _ASSIGNMENT_RE.match(line)
        if match is None:
            raise ValidationError(
                f"MANIFEST.lock line {line_number} is not a scalar assignment"
            )
        key, raw_value = match.groups()
        if not (len(raw_value) >= 2 and raw_value[0] == raw_value[-1] == '"'):
            raise ValidationError(f"MANIFEST.lock line {line_number} is not quoted")
        values[key] = raw_value[1:-1]
    return values


def _series_entries(series_path: Path) -> list[str]:
    try:
        lines = series_path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        raise ValidationError(f"cannot read patches/series: {error}") from error

    entries: list[str] = []
    for line_number, raw_line in enumerate(lines, 1):
        name = raw_line.partition("#")[0].strip()
        if not name:
            continue
        # build.sh treats entries as direct children of patches/.  Reject
        # traversal and nested paths rather than hashing an unexpected file.
        candidate = Path(name)
        if candidate.name != name or name in {".", ".."}:
            raise ValidationError(
                f"patches/series line {line_number} has invalid patch name {name!r}"
            )
        entries.append(name)
    return entries


def _check_hash(manifest: dict[str, str], key: str, expected: str, errors: list[str]) -> None:
    actual = manifest.get(key)
    if actual is None:
        errors.append(f"MANIFEST.lock is missing {key}")
    elif not _HASH_RE.fullmatch(actual):
        errors.append(f"MANIFEST.lock has invalid {key}")
    elif actual != expected:
        errors.append(f"stale MANIFEST.lock: {key} does not match current sources")


def validate(root: Path, *, series_only: bool = False) -> list[str]:
    """Return validation errors for *root*; an empty list means valid."""
    root = root.resolve()
    errors: list[str] = []
    build_dir = root / "build"
    patches_dir = root / "patches"
    version_path = build_dir / "CHROMIUM_VERSION"
    series_path = patches_dir / "series"
    manifest_path = build_dir / "MANIFEST.lock"

    try:
        version_lines = version_path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        errors.append(f"cannot read build/CHROMIUM_VERSION: {error}")
        version_lines = []
    version_values = [line.strip() for line in version_lines if line.strip()]
    if len(version_values) != 1 or not _VERSION_RE.fullmatch(version_values[0]):
        errors.append("build/CHROMIUM_VERSION must contain exactly one valid Chromium version")
        version = version_values[0] if len(version_values) == 1 else None
    else:
        version = version_values[0]

    try:
        entries = _series_entries(series_path)
    except ValidationError as error:
        errors.append(str(error))
        entries = []
    numeric_order = [int(Path(name).name[:4]) for name in entries if re.fullmatch(r"[0-9]{4}-.+\.patch", name)]
    if numeric_order != sorted(numeric_order):
        errors.append("patches/series is out of numeric apply order: " + ", ".join(entries))

    counts = Counter(entries)
    for name, count in sorted(counts.items()):
        if count > 1:
            errors.append(f"patches/series references {name} {count} times")
        patch_path = patches_dir / name
        if not patch_path.is_file():
            errors.append(f"patches/series references missing patch {name}")


    # Every patch in the source tree must be represented exactly once.  This
    # catches a newly added patch accidentally omitted from the release series.
    patch_files = {path.name for path in patches_dir.glob("*.patch")}
    for name in sorted(patch_files - set(counts)):
        errors.append(f"patches/series does not reference patch {name}")
    if series_only:
        return errors
    try:
        manifest = _read_manifest(manifest_path)
    except ValidationError as error:
        errors.append(str(error))
        manifest = {}

    if version is not None and manifest.get("chromium_version") != version:
        errors.append(
            "Chromium version drift: build/CHROMIUM_VERSION and MANIFEST.lock disagree"
        )

    if entries and all((patches_dir / name).is_file() for name in entries):
        series_hash = _sha256(series_path.read_bytes())
        contents_digest = hashlib.sha256()
        for name in entries:
            contents_digest.update(name.encode("utf-8") + b"\0")
            contents_digest.update((patches_dir / name).read_bytes())
            contents_digest.update(b"\0")
        _check_hash(manifest, "patch_series_sha256", series_hash, errors)
        _check_hash(manifest, "patch_contents_sha256", contents_digest.hexdigest(), errors)

    return errors


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--series-only",
        action="store_true",
        help="validate exact patch-series completeness and order without MANIFEST.lock",
    )
    args = parser.parse_args(argv)
    errors = validate(args.root, series_only=args.series_only)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("release baseline valid")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
